### ISSUE TITLE
create a master file/template to document meta-info of all variables  

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/SuPy#83]
a YAML file meant to be a central place to store all meta-info about variable exposed to users, which includes:
- key in short name : used in code and input table headers
- values with details:
  - type: input or output (detailed sub-groups will be shown in examples below).
  - description: full description with unit (if applicable).
  - suews-related variables: SUEWS related variables as in the headers of input tables (e.g. those of `SUEWS_veg.txt`).
  - physics schemes: where this variable is used (e.g. radiation scheme coded `radiationmethod = 3`).
  - data dimensions: dimension info about this variable.
  - loading path: logic used internally by supy to load values from input tables (similar to [this file](https://github.com/UMEP-dev/SuPy/blob/4b5ab18e692a2d32883974a2ac7d301826219aa2/src/supy/var2siteselect.json)).

an example file can be found [here](https://github.com/UMEP-dev/SuPy/blob/sunt05/issue83/dev/var_info.yml), which is generated using [this python script](https://github.com/UMEP-dev/SuPy/blob/sunt05/issue83/dev/gen-var_info_yml.py) with some info filled using other files in this repo - details refer to the code.

**Comment by sunt05** [comment]
Here is an example of an input variable:

```yaml
# `physics scheme` part is what we need to work on
alb:
  type: # one of [input, output]
    input: state # one of [state, method, forcing]
  description: Effective surface albedo (middle of the day value) for summertime.
  suews-related variables: :option:`AlbedoMax <suews:AlbedoMax>`
  loading path:
    Code_Paved: AlbedoMax
    Code_Bldgs: AlbedoMax
    Code_EveTr: AlbedoMax
    Code_DecTr: AlbedoMax
    Code_Grass: AlbedoMax
    Code_Bsoil: AlbedoMax
    Code_Water: AlbedoMax
  data dimensions:
    - (7,)
    - remarks:
        "7: { `suews:Paved`, `suews:Bldgs`, `suews:EveTr`, `suews:DecTr`, `suews:Grass`,
        `suews:BSoil`, `suews:Water`}"
  physics scheme: # ↓ these are what we need to work on ↓ 
    scheme to add:  
      # the actual physics scheme name; currently those ending with "method" in `RunControl.nml` 
      # explicitly list all code associated with the variable
      - code 1
      - code 2

```
